// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJQmF_DPgynmoJZZDWJT2QwS17L1Wg6pM',
    appId: '1:771096097765:web:bfd3d20c84bfbe6854b50c',
    messagingSenderId: '771096097765',
    projectId: 'video-downloader-8',
    authDomain: 'video-downloader-8.firebaseapp.com',
    storageBucket: 'video-downloader-8.firebasestorage.app',
    measurementId: 'G-YWY21LG41F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7APyQ-bnhq8BFSrZQkz36xEb-bvwW6KE',
    appId: '1:771096097765:android:85780ea3a9b3a03e54b50c',
    messagingSenderId: '771096097765',
    projectId: 'video-downloader-8',
    storageBucket: 'video-downloader-8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABWdyHyi02dY6AhkqCQT_tx1lReHCjz8g',
    appId: '1:771096097765:ios:477b7fcf80e0c02054b50c',
    messagingSenderId: '771096097765',
    projectId: 'video-downloader-8',
    storageBucket: 'video-downloader-8.firebasestorage.app',
    iosBundleId: 'com.example.videoDownloader8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABWdyHyi02dY6AhkqCQT_tx1lReHCjz8g',
    appId: '1:771096097765:ios:477b7fcf80e0c02054b50c',
    messagingSenderId: '771096097765',
    projectId: 'video-downloader-8',
    storageBucket: 'video-downloader-8.firebasestorage.app',
    iosBundleId: 'com.example.videoDownloader8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJQmF_DPgynmoJZZDWJT2QwS17L1Wg6pM',
    appId: '1:771096097765:web:2fb5354471d4231654b50c',
    messagingSenderId: '771096097765',
    projectId: 'video-downloader-8',
    authDomain: 'video-downloader-8.firebaseapp.com',
    storageBucket: 'video-downloader-8.firebasestorage.app',
    measurementId: 'G-L7VK1JS9WQ',
  );

}