// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy015kXIR0XG6YaVKreSeoKQV4KIaTfHQ',
    appId: '1:495721062433:web:f5fe13baf7d945f1f54360',
    messagingSenderId: '495721062433',
    projectId: 'flutter-downloader6',
    authDomain: 'flutter-downloader6.firebaseapp.com',
    storageBucket: 'flutter-downloader6.appspot.com',
    measurementId: 'G-JWNB2Y8SJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAokDrmQzCwUnlr2QdTdJBTSWtIW3deyms',
    appId: '1:495721062433:android:5533556eb3ffebf6f54360',
    messagingSenderId: '495721062433',
    projectId: 'flutter-downloader6',
    storageBucket: 'flutter-downloader6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfo5u1ko3MdoPXvAkIpGBmAsh0wH8T0s4',
    appId: '1:495721062433:ios:37ed77ca6b9a376af54360',
    messagingSenderId: '495721062433',
    projectId: 'flutter-downloader6',
    storageBucket: 'flutter-downloader6.appspot.com',
    iosBundleId: 'com.example.videoDownloader6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfo5u1ko3MdoPXvAkIpGBmAsh0wH8T0s4',
    appId: '1:495721062433:ios:bb875079ed7ba296f54360',
    messagingSenderId: '495721062433',
    projectId: 'flutter-downloader6',
    storageBucket: 'flutter-downloader6.appspot.com',
    iosBundleId: 'com.example.videoDownloader6.RunnerTests',
  );
}
